### ISSUE TITLE
Denite won't load when adding this plugin to the Dein.nvim toml

### ISSUE THREAD

**Issue by ghost** [delphinus/vim-denite-memo#6] opened 2020-07-15 13:45 UTC
This works: Denite had properly loaded and worked
```toml
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugin_settings/denite.vim
'''

[[plugins]]
repo= 'Jagua/vim-denite-ghq'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
```
However after adding this plugin to the plugin toml, toml file looks like this:
```toml
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugin_settings/denite.vim
'''

[[plugins]]
repo = 'delphinus/vim-denite-memo'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
```
Then run `:Denite help`, that throwed this:
```vim
[denite] Vim(call):E117: Unknown function: _denite_init
[denite] function denite#helper#call_denite[7]..denite#start[4]..<SNR>85_start[1]..denite#initialize[1]..denite#init#_initialize, lin
e 36
[denite] denite failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
Press ENTER or type command to continue
```

nvim version:
```fish
❯ nvim -v
NVIM v0.5.0-589-g91572ddad
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/mumi/.cache/yay/neovim-git/src/build/config -I/home/mumi/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/mumi/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/mumi/.cache/yay/neovim-git/src/build/include
Compiled by mumi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
python3 and pynvim version:
```
❯ python3 --version
Python 3.8.3
❯ pip3 list | rg pynvim
pynvim                    0.4.1
```

**Comment by ghost** [comment] 2020-07-15 14:06
running `:UpdateRemotePlugins` and restarting nvim doesn't help this. in order to make Denite.nvim loaded again, 
I had to delete this plugin from the toml file and run`call dein#update()` then run `:UpdateRemotePlugins`.

**Comment by delphinus** [comment] 2020-07-31 10:00
Thank you. Reproduced on minimum Dockerfile below. I look further.

https://gist.github.com/delphinus/cdc8cc222e8decfdda08f1a863c7f262

**Comment by delphinus** [comment] 2020-07-31 10:10
A temporal workaround makes good. It is `merged = 0` option for dein.

https://gist.github.com/delphinus/cdc8cc222e8decfdda08f1a863c7f262/revisions

But this is not as I intended. I will investigate more further.

**Comment by ghost** [comment] 2020-08-02 04:10
The workaround worked. Thank you!

**Closed as completed** 2020-08-17 12:51 UTC

**Comment by delphinus** [comment] 2020-08-17 12:54
@iminotech Fixed this and you can use without `merged = 0`. Try it!

https://gist.github.com/delphinus/cdc8cc222e8decfdda08f1a863c7f262 (updated)

**Comment by ghost** [comment] 2020-08-30 08:16
Sorry for late response, tried updating the plugin just now and that correctly worked. Thank you!
